### ISSUE TITLE
Fails with themes that contain "." in the name

### ISSUE THREAD

**Issue by tsbarnes** [refi64/stylepak#10]
I was trying to use pakitheme with the Desert themes from gnome-look.org, and I noticed pakitheme failed on it because the name contains a "." (for example, Desert-Brown-1.3), and that confused flatpak since it determines the name of a package by what comes after the last dot. Basically, "." needs to be escaped to another character, I'm not sure what the best way to do that is, but for now I've worked around it by renaming the themes.

**Comment by refi64** [comment]
basically #9, closing here
