### ISSUE TITLE
How to use stylepak?

### ISSUE THREAD

**Issue by ayu2805** [refi64/stylepak#21]
I am new to linux and trying to install Fluent-gtk-theme but I am having problem installing/using style. Pls explain in a simpler way

**Comment by refi64** [comment]
Could you explain what you tried and what about it didn't work?

**Comment by ayu2805** [comment]
> Could you explain what you tried and what about it didn't work?

hmm I tried everything written on [README.md](https://github.com/refi64/stylepak/blob/master/README.md) installing `ostree appstream-util` and by runnning `stylepak install-system` and `stylepak install-user` on the installation folder

**Comment by refi64** [comment]
did you get any errors when you ran those commands?

**Comment by ayu2805** [comment]
Command not found

**Comment by refi64** [comment]
Try doing `./stylepak`, I should probably update the README to say that instead given that #22 is basically the same core mistake.

**Comment by ayu2805** [comment]
> Try doing `./stylepak`, I should probably update the README to say that instead given that #22 is basically the same core mistake.

Ye i get it, it worked.

**Comment by Arcitec** [comment]
You only need one command, not both. The best one is `stylepak install-system` which installs the theme for all users. The alternative is `stylepak install-user` which installs it only for your account, which is useful if you don't have "sudo" permissions.
