### ISSUE TITLE
Stylepak:148 not found

### ISSUE THREAD

**Issue by chiky-chuky** [refi64/stylepak#22]
Hey. I'm running Mint 20.3 and trying to set Orchis theme to be used by flatpak. I get this error
![2022-01-07_20-31](https://user-images.githubusercontent.com/56842169/148620402-4fa59dd7-9989-444a-90e5-e38cf7c1f2e2.png)
.

**Comment by refi64** [comment]
Stylepak only supports being run with `bash`, try `bash stylepak` or `./stylepak` instead.

**Comment by chiky-chuky** [comment]
> Stylepak only supports being run with `bash`, try `bash stylepak` or `./stylepak` instead.

It worked. thank you!
